/**
 * EIH API-key vault
 * -----------------------------------------------------------------------------
 * One key per AI provider ("slot"): gemini, anthropic, openai. The key is NEVER stored in plain text and is
 * NEVER part of the source code / build output. It is encrypted in the browser
 * with AES-256-GCM before it touches storage.
 *
 * Two protection modes:
 *  - "passphrase" (recommended): key = PBKDF2-SHA256(passphrase, random salt, 600k iterations).
 *      The passphrase is never stored. You re-enter it once per browser session.
 *  - "device": a NON-EXTRACTABLE AES key is generated by the browser and kept in
 *      IndexedDB. Convenient (no passphrase) but protects only against someone
 *      copying/reading your stored data, not against code running in your browser.
 *
 * The decrypted key lives only in a JS variable (memory) while unlocked.
 */

const DEVICE_DB = 'eih-vault';
const DEVICE_STORE = 'keys';

/** One independent vault per provider. 'gemini' keeps the original storage names so existing keys still work. */
export type VaultSlot = 'gemini' | 'anthropic' | 'openai';
export const VAULT_SLOTS: VaultSlot[] = ['gemini', 'anthropic', 'openai'];
const lsName = (slot: VaultSlot) => (slot === 'gemini' ? 'eih.vault.v1' : `eih.vault.v1.${slot}`);
const deviceKeyId = (slot: VaultSlot) => (slot === 'gemini' ? 'device-key-v1' : `device-key-v1-${slot}`);
const LS_VAULT = lsName('gemini');
const AAD = new TextEncoder().encode('eih-vault-v1');
const PBKDF2_ITERATIONS = 600_000;

export type VaultMode = 'passphrase' | 'device';

interface VaultRecord {
  v: 1;
  mode: VaultMode;
  iter?: number;
  salt?: string;
  iv: string;
  ct: string;
  createdAt: string;
}

export interface VaultState {
  hasVault: boolean;
  unlocked: boolean;
  mode: VaultMode | null;
}

export class VaultLockedError extends Error {
  constructor(message = 'The AI key is locked. Unlock it in AI Settings.') {
    super(message);
    this.name = 'VaultLockedError';
  }
}

/* ----------------------------- small helpers ----------------------------- */

function b64encode(buf: ArrayBuffer | Uint8Array): string {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += String.fromCharCode(bytes[i]);
  return btoa(s);
}

function b64decode(str: string): Uint8Array {
  const s = atob(str);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

function randomBytes(n: number): Uint8Array {
  const a = new Uint8Array(n);
  crypto.getRandomValues(a);
  return a;
}

async function deriveKey(passphrase: string, salt: Uint8Array, iterations: number): Promise<CryptoKey> {
  const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(passphrase), 'PBKDF2', false, [
    'deriveKey',
  ]);
  return crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt: salt as BufferSource, iterations, hash: 'SHA-256' },
    material,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt', 'decrypt'],
  );
}

/* ------------------------- device key (IndexedDB) ------------------------- */

function openDeviceDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DEVICE_DB, 1);
    req.onupgradeneeded = () => {
      req.result.createObjectStore(DEVICE_STORE);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function idbGet<T>(key: string): Promise<T | undefined> {
  const db = await openDeviceDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(DEVICE_STORE, 'readonly');
    const r = tx.objectStore(DEVICE_STORE).get(key);
    r.onsuccess = () => resolve(r.result as T | undefined);
    r.onerror = () => reject(r.error);
  });
}

async function idbPut(key: string, value: unknown): Promise<void> {
  const db = await openDeviceDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(DEVICE_STORE, 'readwrite');
    tx.objectStore(DEVICE_STORE).put(value, key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function idbDelete(key: string): Promise<void> {
  const db = await openDeviceDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(DEVICE_STORE, 'readwrite');
    tx.objectStore(DEVICE_STORE).delete(key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function getOrCreateDeviceKey(slot: VaultSlot): Promise<CryptoKey> {
  const existing = await idbGet<CryptoKey>(deviceKeyId(slot));
  if (existing) return existing;
  const key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']);
  await idbPut(deviceKeyId(slot), key);
  return key;
}

/* ------------------------------ vault state ------------------------------ */

const memoryKeys = new Map<VaultSlot, string>();
const listeners = new Set<() => void>();
const snapshots = new Map<VaultSlot, VaultState>();

function readRecord(slot: VaultSlot = 'gemini'): VaultRecord | null {
  try {
    const raw = localStorage.getItem(lsName(slot));
    if (!raw) return null;
    const rec = JSON.parse(raw) as VaultRecord;
    if (rec && rec.v === 1 && rec.ct && rec.iv) return rec;
    return null;
  } catch {
    return null;
  }
}

function computeState(slot: VaultSlot): VaultState {
  const rec = readRecord(slot);
  return { hasVault: !!rec, unlocked: memoryKeys.has(slot), mode: rec ? rec.mode : null };
}

function sameState(a: VaultState, b: VaultState): boolean {
  return a.hasVault === b.hasVault && a.unlocked === b.unlocked && a.mode === b.mode;
}

function emit(): void {
  // Keep the same object when nothing changed so useSyncExternalStore does not re-render needlessly.
  for (const slot of VAULT_SLOTS) {
    const next = computeState(slot);
    const prev = snapshots.get(slot);
    if (!prev || !sameState(prev, next)) snapshots.set(slot, next);
  }
  listeners.forEach((l) => l());
}
for (const slot of VAULT_SLOTS) snapshots.set(slot, computeState(slot));

/** For React's useSyncExternalStore. */
export function subscribeVault(fn: () => void): () => void {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}
export function getVaultSnapshot(slot: VaultSlot = 'gemini'): VaultState {
  return snapshots.get(slot) ?? computeState(slot);
}

/* ------------------------------- public API ------------------------------- */

export function normalizeApiKey(raw: string): string {
  return raw.replace(/\s+/g, '').replace(/^["']|["']$/g, '');
}

/** Encrypt and store the key. Replaces any existing key. The key is then held in memory (unlocked). */
export async function saveKey(apiKey: string, mode: VaultMode, passphrase?: string, slot: VaultSlot = 'gemini', minLength = 20): Promise<void> {
  const clean = normalizeApiKey(apiKey);
  if (clean.length < minLength) throw new Error('That does not look like a valid API key.');
  const iv = randomBytes(12);
  const plain = new TextEncoder().encode(clean);
  let record: VaultRecord;

  if (mode === 'passphrase') {
    if (!passphrase || passphrase.length < 8) throw new Error('Passphrase must be at least 8 characters.');
    const salt = randomBytes(16);
    const key = await deriveKey(passphrase, salt, PBKDF2_ITERATIONS);
    const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: iv as BufferSource, additionalData: AAD }, key, plain);
    record = {
      v: 1,
      mode,
      iter: PBKDF2_ITERATIONS,
      salt: b64encode(salt),
      iv: b64encode(iv),
      ct: b64encode(ct),
      createdAt: new Date().toISOString(),
    };
  } else {
    await idbDelete(deviceKeyId(slot)); // fresh device key for each saved key
    const key = await getOrCreateDeviceKey(slot);
    const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: iv as BufferSource, additionalData: AAD }, key, plain);
    record = { v: 1, mode, iv: b64encode(iv), ct: b64encode(ct), createdAt: new Date().toISOString() };
  }

  localStorage.setItem(lsName(slot), JSON.stringify(record));
  memoryKeys.set(slot, clean);
  emit();
}

/** Decrypt the stored key into memory. Passphrase is required in "passphrase" mode. */
export async function unlock(passphrase?: string, slot: VaultSlot = 'gemini'): Promise<void> {
  const rec = readRecord(slot);
  if (!rec) throw new Error('No API key has been saved yet.');
  try {
    let key: CryptoKey;
    if (rec.mode === 'passphrase') {
      if (!passphrase) throw new Error('Enter your passphrase.');
      key = await deriveKey(passphrase, b64decode(rec.salt as string), rec.iter ?? PBKDF2_ITERATIONS);
    } else {
      const k = await idbGet<CryptoKey>(deviceKeyId(slot));
      if (!k) throw new Error('The device key is missing (browser data was cleared). Please add your API key again.');
      key = k;
    }
    const plain = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: b64decode(rec.iv) as BufferSource, additionalData: AAD },
      key,
      b64decode(rec.ct) as BufferSource,
    );
    memoryKeys.set(slot, new TextDecoder().decode(plain));
    emit();
  } catch (e) {
    if (e instanceof Error && e.message && e.name !== 'OperationError') throw e;
    throw new Error('Wrong passphrase, or the stored key is corrupted.');
  }
}

/** Forget the decrypted key (the encrypted copy stays stored). */
export function lock(slot: VaultSlot = 'gemini'): void {
  memoryKeys.delete(slot);
  emit();
}

/** Permanently remove the encrypted key (and the device key if any). */
export async function deleteVault(slot: VaultSlot = 'gemini'): Promise<void> {
  memoryKeys.delete(slot);
  localStorage.removeItem(lsName(slot));
  try {
    await idbDelete(deviceKeyId(slot));
  } catch {
    /* ignore */
  }
  emit();
}

/** Used only by the AI client. Throws VaultLockedError when locked / missing. */
export function getKey(slot: VaultSlot = 'gemini'): string {
  const k = memoryKeys.get(slot);
  if (k) return k;
  throw new VaultLockedError(
    readRecord(slot) ? 'The AI key is locked. Unlock it in AI Settings.' : 'No API key saved yet. Add it in AI Settings.',
  );
}

/** Try silent unlock for device-mode vaults (call once on app start). Covers every provider. */
export async function tryAutoUnlock(): Promise<void> {
  for (const slot of VAULT_SLOTS) {
    const rec = readRecord(slot);
    if (rec && rec.mode === 'device' && !memoryKeys.has(slot)) {
      try {
        await unlock(undefined, slot);
      } catch {
        /* stays locked */
      }
    }
  }
}

/* --------------------- legacy plain-text key clean-up --------------------- */

export interface LegacyKeyHit {
  storage: 'localStorage' | 'sessionStorage';
  name: string;
  preview: string; // masked, never the full key
}

const KEY_PATTERN = /(AIza[0-9A-Za-z_-]{30,}|AQ\.[0-9A-Za-z_-]{20,})/;

function mask(v: string): string {
  const m = v.match(KEY_PATTERN);
  const s = m ? m[1] : v;
  return s.length > 8 ? `${s.slice(0, 3)}••••••••${s.slice(-2)}` : '••••••••';
}

/** Finds Gemini keys that older steps stored in plain text (any localStorage/sessionStorage entry that looks like one). */
export function findLegacyKeys(): LegacyKeyHit[] {
  const hits: LegacyKeyHit[] = [];
  const scan = (store: Storage, label: 'localStorage' | 'sessionStorage') => {
    for (let i = 0; i < store.length; i++) {
      const name = store.key(i);
      if (!name || name === LS_VAULT) continue;
      const val = store.getItem(name) ?? '';
      if (KEY_PATTERN.test(val)) hits.push({ storage: label, name, preview: mask(val) });
    }
  };
  try {
    scan(localStorage, 'localStorage');
    scan(sessionStorage, 'sessionStorage');
  } catch {
    /* storage unavailable */
  }
  return hits;
}

/** Import the first legacy key found into the vault (as the single shared key). Returns the key. */
export function readLegacyKey(hit: LegacyKeyHit): string | null {
  const store = hit.storage === 'localStorage' ? localStorage : sessionStorage;
  const m = (store.getItem(hit.name) ?? '').match(KEY_PATTERN);
  return m ? m[1] : null;
}

export function wipeLegacyKeys(hits: LegacyKeyHit[]): void {
  for (const h of hits) {
    (h.storage === 'localStorage' ? localStorage : sessionStorage).removeItem(h.name);
  }
}
