import { useMemo, useRef, useState } from 'react';
import { AlertTriangle, Loader2, Sparkles } from 'lucide-react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db, newId, nowIso } from '@/db/db';
import type { Project } from '@/db/types';
import { useApiKey } from '@/hooks/useApiKey';
import { useGraphSource } from '@/hooks/useGraphSource';
import { generateProjectFlow } from '@/services/projectAI';
import { describeError, isGeminiError } from '@/services/geminiService';
import Section from '@/components/ui/Section';
import MermaidDiagram from '@/components/flow/MermaidDiagram';

export default function ProjectFlowTab({ project }: { project: Project }) {
 const source=useGraphSource(); const apiKey=useApiKey();
 const requirements=useLiveQuery(()=>db.requirements.where('projectId').equals(project.id).toArray(),[project.id]);
 const artifacts=useLiveQuery(()=>db.artifacts.where('projectId').equals(project.id).filter(a=>a.kind==='diagram').toArray(),[project.id]);
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [flow,setFlow]=useState(''); const abort=useRef<AbortController|null>(null);
 const latest=useMemo(()=>[...(artifacts??[])].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],[artifacts]);
 const freshness=useMemo(()=>{
   if(!latest||!source)return false;
   const generated=new Date(latest.createdAt).getTime();
   const ids=new Set(project.applicationIds??[]);
   return [...source.applications.filter(a=>ids.has(a.id)),...source.modules.filter(m=>(project.moduleIds??[]).includes(m.id)),...source.functionalities.filter(f=>(project.functionalityIds??[]).includes(f.id)),...(requirements??[])].some(x=>new Date(x.updatedAt).getTime()>generated);
 },[latest,source,project,requirements]);
 const currentFlows=useMemo(()=>source?source.functionalities.filter(f=>(project.functionalityIds??[]).includes(f.id)).map(f=>f.processFlow).filter(Boolean):[],[source,project.functionalityIds]);
 const generate=async()=>{
   if(!source||!requirements?.length||!apiKey)return;
   setBusy(true);setError('');setNotice('');
   const controller=new AbortController();abort.current=controller;
   try{
     const result=await generateProjectFlow(project,requirements,currentFlows,{applications:source.applications,modules:source.modules,screens:source.screens,functionalities:source.functionalities},controller.signal);
     const t=nowIso();
     await db.artifacts.add({id:newId(),createdAt:t,updatedAt:t,projectId:project.id,kind:'diagram',title:result.data.title||('Future-state flow · '+project.name),content:result.data.mermaid,version:(latest?.version??0)+1,status:'draft',approvals:[],generatedBy:{model:result.model,at:t}});
     setFlow(result.data.mermaid);setNotice('Generated with '+result.model+'. Update the flow again after application or requirement changes.');
   }catch(err){if(!(isGeminiError(err)&&err.code==='ABORTED'))setError(describeError(err));}
   finally{setBusy(false);abort.current=null;}
 };
 const displayed=flow||latest?.content||'';
 return <div className="space-y-6">
   <Section title="Future-state process flow" description="Gemini compares the existing documented flows with the project's requirements and proposes how the process should work after implementation.">
     {freshness&&<p className="mb-4 flex items-start gap-2 rounded border border-outline-variant bg-surface-low p-3 text-body-md"><AlertTriangle size={16} className="mt-0.5 shrink-0"/>Application or requirement data changed after this flow was generated. Regenerate it before using it for analysis or design.</p>}
     <div className="flex flex-wrap items-center gap-3">
       {busy?<button type="button" className="btn btn-secondary" onClick={()=>abort.current?.abort()}><Loader2 size={15} className="animate-spin"/>Generating…</button>:<button type="button" className="btn btn-primary" disabled={!apiKey||!requirements?.length} onClick={()=>void generate()}><Sparkles size={16}/>Generate / update with Gemini</button>}
       {!apiKey&&<span className="text-body-md text-on-surface-variant">Configure Gemini in Settings first.</span>}
       {!requirements?.length&&<span className="text-body-md text-on-surface-variant">Add requirements before generating a future-state flow.</span>}
     </div>
     {notice&&<p role="status" className="mt-4 rounded border border-outline-variant bg-surface-low p-3 text-body-md">{notice}</p>}
     {error&&<p role="alert" className="mt-4 rounded border border-error bg-error-container p-3 text-body-md text-error">{error}</p>}
   </Section>
   {displayed&&<Section title={latest?.title??'Generated flow'} description={latest?.generatedBy?.model?('Generated by '+latest.generatedBy.model+' · '+new Date(latest.createdAt).toLocaleString()):'Generated flow'}><MermaidDiagram source={displayed}/><details className="mt-4 rounded border border-outline-variant"><summary className="cursor-pointer px-4 py-2 text-body-md font-medium">Mermaid source</summary><pre className="overflow-x-auto border-t border-outline-variant p-4 font-mono text-code">{displayed}</pre></details></Section>}
 </div>;
}
